### ISSUE TITLE
Enchanting Rune of Silk Touch sacrifice bugged

### ISSUE THREAD

**Issue by Crazy-KSK** [Xilef11/Runes-of-Wizardry#23]
it says Invalid sacrifice no matter how many levels, gold blocks, diamond shovels or picks I throw at it
the fortune rune works

**Comment by Xilef11** [comment]
I can confirm the issue, but I have no clue what causes it, especially since the rune of fortune works (they are [mostly](https://github.com/Xilef11/runesofwizardry-classics/blob/master/src/main/java/xilef11/mc/runesofwizardry_classics/runes/RuneEnchantingFortune.java) [identical](https://github.com/Xilef11/runesofwizardry-classics/blob/master/src/main/java/xilef11/mc/runesofwizardry_classics/runes/RuneEnchantingSilkTouch.java)). It seems that it doesn't respect the wildcard damage on the tools. ALso the rune of Fortune accepts a shovel somehow.
