### ISSUE TITLE
Conflict with... Some mod

### ISSUE THREAD

**Issue by Phonavis** [Xilef11/Runes-of-Wizardry#49]
So, this post is more of a placement and story post until I figure out the invisible conflict happening here.
Crash Report - https://pastebin.com/nVBUVrnG

So, to get an idea of how this happened, I used Crafttweaker's lovely recipe.removeAll()
Then that issue above happened.
So, to check if it was a conflict, I tested an instance with just craft tweaker, guideapi, and Runes of Wizardry
No issue.

So here I am thinking, fine, must be an issue with another mod that uses GuideAPI, and so I add them all to said seperate instance.
No issue.

So I start thinking "What if I remove Guide API from the mix?"
No issue.

So, to get this straight. It's a magical conflict when Runes of Wizardry attempts to register with guide api in the presence of another mod in my load order that does not register with guide api, and when all crafting recipes have been removed.

I would appreciate some insights into the behind the scenes workings or any ideas while I go through my 300+ mod load order hahahahaha

**Comment by Xilef11** [comment]
The error happens when I create the recipe page for the Dust Pouch. I create a list of all possible recipes and get the first element, which should be the basic crafting of the pouch. Since you remove all recipes with CraftTweaker, it makes sense that the list is empty, thus causing the error.

It's Guide-API that calls this bit of code (and therefore causes the error), so if you remove it there won't be an error (as the guide book won't be built). What's weird is that the error doesn't happen with only GuideAPI, CraftTweaker and Runes of Wizardry (try adding the classic pack to the mix). Did you remove the recipes when you tested?

I highly doubt it's a conflict with another mod, but I would start by trying with only those that show up *before* Guide-API in the load order (shown in the crash report). If that doesn't do it, the fastest way to find a conflict is a binary search (split the potential conflicting mods in half, try both halves separately. repeat with the half that causes the error until there's only one mod left).

Links to the code (for reference)
[WizardryGuide.handlePost](https://github.com/Xilef11/Runes-of-Wizardry/blob/master/src/main/java/com/zpig333/runesofwizardry/integration/guideapi/WizardryGuide.java#L63)
[Getting pouch recipe (erroring line)](https://github.com/Xilef11/Runes-of-Wizardry/blob/master/src/main/java/com/zpig333/runesofwizardry/integration/guideapi/category/CategoryBasic.java#L63)
[Utils.getRecipesForOutput](https://github.com/Xilef11/Runes-of-Wizardry/blob/master/src/main/java/com/zpig333/runesofwizardry/util/Utils.java#L117)

**Comment by Phonavis** [comment]
So this is interesting.
I ended up with about 20 mods and decided to put them in a seperate instance (Including ROW, ROW Classic, Guide Api, Craft tweaker) and it still crashed like instance 1. Then I slowly weeded out all mods untill I was down to the 4 and still crashed.

So I thought "Maybe it's a corrupt file?" so I copied the files over to my working instance with all 4 and deleted the previous 4, and magically it still worked.

I've confirmed it's the exact same script among all 3 instances, and it is indeed removing all recipes in the working instance, and yet
It's not crashing.

I don't even know. God help me.

**Comment by Xilef11** [comment]
maybe a corrupt *config* file?

I can't really think of a reason why removing all recipes would NOT cause this error...

**Comment by Phonavis** [comment]
Deleted the config file from instance 2 (The Working One) with the jar file from Instance 1/3 (The crashing one)
Still loaded fine.
I just can't even.
So if it's a recipe issue do you think adding a random placeholder recipe after removing all of them to the bag will fix it? Or will it not like having a new recipe either?

**Comment by Xilef11** [comment]
As long as there is at least one recipe for the pouch, this error should not happen (may happen for other items though).

Just FYI, removing ALL recipes may prevent the pouch from working, as filling/emptying is done with a (special) crafting recipe. I don't know how this is handled by CraftTweaker.

**Comment by Phonavis** [comment]
Just to double check how the bag acts in the working instance, attempting to set the dust does not work nor does the bag itself have a recipe

So it basically busts the special method to fill it too. Fantastic. 
At this rate gonna have to use a roundabout loop if-else method to remove all mods one by one besides ROW. Still curious why this one instance is working fine though.

**Comment by Xilef11** [comment]
Minecraft/Forge weirdness that causes a fake/empty recipe to still exist in the list? 

I'll look into CraftTweaker to see if I can better support it. Hopefully there's a way to mark a recipe as "must be explicitly removed" or "unaffected by the removeAll command". might take a few days, though.

I'll also tweak the code for the guide, that way if someone wants to add more than one pouch recipe they will actually show up (and not crash if there's none).

**Comment by Xilef11** [comment]
With v1.12.2-0.9.2 it should no longer crash when removing all recipes.

Unfortunately, there does not seem to be a way to prevent a recipe from being affected by CraftTweaker's removeAll command. For the pouch to work, you can remove all recipes from this mod except the instance of **com.zpig333.runesofwizardry.recipe.RecipeDustPouch**. It has a registry name of **runesofwizardry:dustpouch**

I'm curious as to what kind of pack you're making that you need to remove *all* recipes...

**Comment by Phonavis** [comment]
Originally I was planning on making a learning questbook modpack oriented around the idea of "Exchange"

Each item would be assigned a EMC value and you'd unlock items by doing certain tasks then sticking it in the ol' exchange tablet. 

Was a dumb idea though, regretfully many mods have issues with removing all recipes, so I've shifted my goal a bit to abandon the idea of pure emc focused. 
Was pretty hard to think of good tasks anyways other than "Grind EMC for Item B to allow you to grind more EMC for item C which can replace Item A"

I might look into it again in the future, depending on my creativity.

Anyways new update works without any recipes, thanks for your time
